---
- name: Create ZShell XDG directory.
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config/zsh
    - ~/.local/state/zsh

- name: Copy .zshenv to home directory
  ansible.builtin.copy:
    src: .zshenv
    dest: ~/.zshenv
    mode: "0600"

- name: Copy .zshrc to zsh config directory
  ansible.builtin.copy:
    src: .zshrc
    dest: ~/.config/zsh/.zshrc
    mode: "0600"
