- name: Create XDG Base Directories.
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0700"
    state: directory
  loop:
    - ~/.config
    - ~/.cache
    - ~/.local
    - ~/.local/share
    - ~/.local/state
